cloudcannon:
  input: "./"   # Diretório de entrada, onde seus arquivos estão localizados
  output: "./_site"   # Diretório de saída, onde seu site será construído
  collections_config:
    pages:
      output: true
      path: ""
    posts:
      output: true
      path: "posts"
  collections:
    pages:
      output: true
      path: ""
    posts:
      output: true
      path: "posts"
  data_config:
    settings:
      output: true
  files_config:
    output: true
  static:
    assets:
      - "images"
      - "css"
      - "js"
