cloudcannon:
  input: "./src"
  output: "./public"  # Diretório de saída (ajuste conforme necessário)
  collections_config:
    pages:
      output: true
      path: "pages"
    blog:
      output: true
      path: "content/blog"
    docs:
      output: true
      path: "content/docs"
    insights:
      output: true
      path: "content/insights"
    products:
      output: true
      path: "content/products"
  data_config:
    config:
      output: true
  files_config:
    output: true
  static:
    assets:
      - "assets/scripts"
      - "assets/styles"
      - "images"
