collections_config:
  posts:
    name: Blog Posts
    label: "📝 Articles"
    folder: "content/blog"
    create: true
    fields:
      - name: title
        label: Title
        type: text
      - name: description
        label: Description
        type: text

inputs:
  site:
    title:
      label: Site Title
      type: text
