# cloudcannon.config.yml

source: src

collections_config:
  blog:
    path: content/blog/
    output: true
  docs:
    path: content/docs/
    output: true
  insights:
    path: content/insights/
    output: true
  products:
    path: content/products/
    output: true
  pages:
    path: pages/
    output: true

# Define static assets and public resources
static_assets:
  public: public/

# Customizing navigation and footer links
navigation:
  navBarLinks:
    - name: "Home"
      url: "/"
    - name: "Products"
      url: "/products"
    - name: "Services"
      url: "/services"
    - name: "Blog"
      url: "/blog"
    - name: "Contact"
      url: "/contact"
  footerLinks:
    - section: "Product"
      links:
        - name: "Tools & Equipment"
          url: "/tools-equipment"
        - name: "Construction Services"
          url: "/construction-services"
        - name: "Pricing"
          url: "/pricing"
    - section: "Company"
      links:
        - name: "About us"
          url: "/about"
        - name: "Blog"
          url: "/blog"
        - name: "Careers"
          url: "/careers"
        - name: "Customers"
          url: "/customers"
  socialLinks:
    facebook: "https://facebook.com/yourprofile"
    twitter: "https://twitter.com/yourprofile"
    github: "https://github.com/yourprofile"
    linkedin: "https://linkedin.com/in/yourprofile"
    instagram: "https://instagram.com/yourprofile"

# Paths
paths:
  assets: assets/
  scripts: assets/scripts/
  styles: assets/styles/
  components: components/
  meta: components/Meta.astro
  sections: components/sections/
  theme_icon: components/ThemeIcon.astro
  ui_components: components/ui/
  content: content/
  blog: content/blog/
  docs: content/docs/
  insights: content/insights/
  products: content/products/
  config: content/config.ts
  data_files: data_files/
  images: images/
  layouts: layouts/
  main_layout: layouts/MainLayout.astro
  pages: pages/
  custom_404: pages/404.astro
  blog_pages: pages/blog/
  localized_content: pages/fr/
  contact_page: pages/contact.astro
  home_page: pages/index.astro
  insights_pages: pages/insights/
  products_pages: pages/products/
  robots_txt: pages/robots.txt.ts
  services_page: pages/services.astro
  utils: utils/

# SEO Configuration
seo:
  site: "ScrewFast"
  title: "ScrewFast: Hardware Tools & Construction Services"
  description: "Top-quality hardware tools and expert construction services for every project need."
  og:
    title: "ScrewFast: Hardware Tools & Construction Services"
    description: "Discover top-quality hardware tools and services"
    url: "https://screwfast.uk"
    image: "/banner-pattern.svg"
  twitter:
    card: "summary_large_image"
    site: "@screwfast"
    title: "ScrewFast: Hardware Tools & Construction Services"
    description: "Discover top-quality hardware tools and services"
    image: "/banner-pattern.svg"
  structured_data:
    "@context": "https://schema.org"
    "@type": "WebSite"
    name: "ScrewFast"
    url: "https://screwfast.uk"
    description: "Discover top-quality hardware tools and services"

# Deployment and Security
deployment:
  provider: "vercel"
  vercel_config:
    headers:
      - source: "/(.*)"
        headers:
          - key: "Content-Security-Policy"
            value: "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self';"
          - key: "X-Content-Type-Options"
            value: "nosniff"
          - key: "Referrer-Policy"
            value: "no-referrer-when-downgrade"
          - key: "Strict-Transport-Security"
            value: "max-age=31536000; includeSubDomains; preload"
          - key: "X-Frame-Options"
            value: "DENY"
          - key: "X-XSS-Protection"
            value: "1; mode=block"
    redirects:
      - source: "/old-path"
        destination: "/new-path"
        permanent: true
